spring:
  dataSource:
    happyboot: 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/happy_springboot?characterEncoding=utf8&useSSL=true
      username: root
      password: admin
    extdsnames: happyboot01,happyboot02
    happyboot01:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/happyboot01?characterEncoding=utf8&useSSL=true
      username: root
      password: admin 
    happyboot02:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/happyboot02?characterEncoding=utf8&useSSL=true
      username: root
      password: admin      


  dubbo: 
    application:
#注册在注册中心的名称
      id: dubbo-springboot-starter-provider
      name: dubbo-springboot-starter-provider
#注册中心地址，zookeeper集群，启动输出可以看见链接了多个
#单zookeeper服务：
    registry: 
      address: zookeeper://192.168.0.10:2181?backup=192.168.0.20:2181,192.168.0.30:2181
#暴露服务方式
    protocol:
      id: dubbo
#默认名称，勿修改
      name: dubbo
#暴露服务端口 
      port: 20880
      status : server
#调用dubbo组建扫描的项目路径
    scan: com.happy.springboot.service.dubbo.service.impl
    
        
dbShardingStrategy: 
    mod6000: 
      totalDb: 6
      totalTable: 6000
      numLen: 2
      start: 1
      
tableShardingStrategy:
    mod6000: 
      totalTable: 6000
      numLen: 4
      start: 0  
      
      