spring:
  dataSource:
    happyboot: 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/happy_springboot?characterEncoding=utf8&useSSL=true
      username: root
      password: admin
    extdsnames: happyboot01,happyboot02
    happyboot01:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/happyboot01?characterEncoding=utf8&useSSL=true
      username: root
      password: admin 
    happyboot02:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/happyboot02?characterEncoding=utf8&useSSL=true
      username: root
      password: admin      

dubbo:
 application:
     name: dubbo-springboot-starter-provider
 registry:
     address: zookeeper://192.168.0.10:2181?backup=192.168.0.20:2181,192.168.0.30:2181
 protocol: dubbo
      
dbShardingStrategy:
    mod6000: 
      totalDb: 6
      totalTable: 6000
      numLen: 2
      start: 1
      
tableShardingStrategy:
    mod6000: 
      totalTable: 6000
      numLen: 4
      start: 0  
      
      